index:
    path: /inicio
    controller: App\Controller\HomeController::index

animales:
  path: /animales/{nombre}/{apellidos}
  controller: App\Controller\HomeController::animales
  defaults: { nombre: 'nombre', apellidos: 'por defecto' }
  methods: [POST,GET]
  requirements:
    nombre: "[a-zA-Z ]+"
    apellidos: '[0-9 ]+'


redirigir:
    path: /redirigir
    controller: App\Controller\HomeController::redirigir
  